### ISSUE TITLE
Link to Boston example data is broken

### ISSUE THREAD

**Issue by asitemade4u** [eyeseast/datasette-geojson-map#22]
In the documentation.
The link displayed in the example is wrong: `wget -O neighborhoods.geojson https://opendata.arcgis.com/datasets/3525b0ee6e6b427f9aab5d0a1d0a1a28_0`

**Comment by mroswell** [comment]
Came here to report the same. Closest I could find was: 
`https://hub.arcgis.com/datasets/fefd5fb156d9419e80a3944a62bd64ab_1/explore?location=42.312357%2C-71.056829%2C12.60`
But I couldn't find the actual download link.
